const DEFAULT_SOURCE_REGISTRY = [
  "https://www.forebet.com",
  "https://www.predictz.com",
  "https://www.windrawwin.com",
  "https://www.betensured.com",
  "https://www.olbg.com",
  "https://www.soccerpunter.com",
  "https://www.soccerstats.com",
  "https://www.statarea.com",
  "https://www.vitibet.com",
  "https://www.bettingclosed.com",
  "https://www.freesupertips.com",
  "https://www.zulubet.com",
  "https://www.protipster.com",
  "https://www.bettingexpert.com",
  "https://www.betsapi.com",
  "https://www.sportytrader.com",
  "https://www.footballpredictions.com",
  "https://www.betshoot.com",
  "https://www.tipstrr.com",
  "https://www.tips180.com",
  "https://www.scorepredictor.net",
  "https://www.oddsportal.com",
  "https://www.flashscore.com",
  "https://www.goaloo.com",
  "https://www.betrush.com",
  "https://www.bettin.gs",
  "https://www.bestbettingtips.org",
  "https://www.tips.gg",
  "https://www.bettingtips1x2.com",
  "https://www.kickoff.co.uk",
];

module.exports = {
  DEFAULT_SOURCE_REGISTRY,
};
